name: security-gate
version: "1.0.0"
description: "L3 Security Path Protection - block modifications to security/auth paths"
id: QL-POLICY-002

enabled: true
priority: 0  # Highest priority - run first

triggers:
  - event: pre_file_write
  - event: pre_file_edit
  - event: pre_file_create
  - event: pre_file_delete

conditions:
  file_patterns:
    include:
      - "**/security/**"
      - "**/auth/**"
      - "**/authentication/**"
      - "**/authorization/**"
      - "**/*auth*.ts"
      - "**/*auth*.js"
      - "**/*auth*.py"
      - "**/*security*.ts"
      - "**/*security*.js"
      - "**/*security*.py"
      - "**/middleware/auth*"
      - "**/guards/**"
      - "**/permissions/**"
      - "**/roles/**"
      - "**/tokens/**"
      - "**/jwt/**"
      - "**/oauth/**"
      - "**/credentials/**"
      - "**/secrets/**"
      - "**/encryption/**"
      - "**/crypto/**"
      - "**/pii/**"

# ============================================
# IMMEDIATE ACTIONS ON MATCH
# ============================================
on_match:
  - action: alert
    severity: critical
    message: |
      SECURITY PATH DETECTED

      File: {{ file_path }}
      Operation: {{ operation }}
      Risk Grade: L3

      This file is in a critical security path.

  - action: assign_orbit
    orbit: orbit-judge
    reason: "Security paths require Judge oversight"

  - action: classify
    risk_grade: L3
    reason: "All security path operations are L3"

# ============================================
# MODIFICATION BLOCKING
# ============================================
blocking:
  enabled: true
  operations:
    - write_to_file
    - edit_file
    - create_file
    - delete_file

  block_conditions:
    - condition: "no_pass_verdict"
      check: ".agent/staging/AUDIT_REPORT.md does not contain 'VERDICT: PASS'"
      message: "Security path blocked. Formal audit required."

    - condition: "no_l3_seal"
      check: "docs/META_LEDGER.md does not contain L3 seal for this operation"
      message: "L3 seal required for security modifications."

  on_block:
    severity: block
    message: |
      BLOCKED: Security path modification requires formal L3 seal.

      Required steps:
      1. Run /aegis-audit to generate formal review
      2. Obtain PASS verdict
      3. L3 seal will be recorded in META_LEDGER.md
      4. Only then can modifications proceed

      Operation: {{ operation }}
      Target: {{ file_path }}

# ============================================
# SECURITY STUB DETECTION
# ============================================
stub_detection:
  enabled: true
  patterns:
    - name: todo_auth
      pattern: "TODO.*auth|FIXME.*auth|TODO.*security"
      message: "Authentication/security TODO detected"

    - name: not_implemented
      pattern: "throw.*NotImplemented|raise.*NotImplemented|pass\\s*#.*auth"
      message: "Unimplemented security logic"

    - name: hardcoded_credential
      pattern: "password\\s*=\\s*['\"][^'\"]+['\"]|api_key\\s*=\\s*['\"][^'\"]+['\"]"
      message: "Hardcoded credential detected"

    - name: bypass_comment
      pattern: "//\\s*disable.*auth|//\\s*skip.*security|//\\s*temp.*bypass"
      message: "Security bypass comment"

    - name: always_true_auth
      pattern: "return\\s+true\\s*//|return\\s+true\\s*;\\s*//.*temp"
      message: "Auth always returns true (potential bypass)"

    - name: mock_in_prod
      pattern: "mock.*auth|fake.*token|test.*credential"
      exclude_paths: ["**/tests/**", "**/__mocks__/**"]
      message: "Mock authentication in production code"

  on_detection:
    severity: block
    action: veto
    message: |
      SECURITY STUB DETECTED

      Pattern: {{ pattern_name }}
      Location: {{ location }}
      Match: {{ match }}

      Security logic must be fully implemented before code can proceed.
      No placeholders, TODOs, or bypasses allowed in security paths.

# ============================================
# L3 SEAL REQUIREMENT
# ============================================
seal_requirement:
  description: "All L3 operations require formal seal in META_LEDGER"
  seal_format:
    entry_type: L3_AUTHORIZATION
    required_fields:
      - timestamp
      - auditor (must be orbit-judge)
      - target_files
      - security_review_hash
      - explicit_approval
  verification:
    location: docs/META_LEDGER.md
    check: "Entry with L3_AUTHORIZATION for {{ file_path }}"
    recency: "24h"  # Seal valid for 24 hours

  on_missing_seal:
    severity: block
    message: "L3 seal required. Run /aegis-gate with security focus."

# ============================================
# SECURITY AUDIT CHECKLIST
# ============================================
audit_checklist:
  - name: no_hardcoded_secrets
    check: "No hardcoded passwords, API keys, tokens"
    severity: critical

  - name: no_bypass_mechanisms
    check: "No always-true auth, disabled checks, test credentials in prod"
    severity: critical

  - name: input_validation
    check: "All inputs validated before processing"
    severity: high

  - name: error_messages
    check: "Error messages don't leak sensitive info"
    severity: medium

  - name: logging_sanitized
    check: "Logs don't contain credentials or PII"
    severity: high

  - name: encryption_used
    check: "Sensitive data encrypted at rest and in transit"
    severity: high

  - name: principle_least_privilege
    check: "Permissions are minimally scoped"
    severity: medium

# ============================================
# GHOST PATH DETECTION
# ============================================
ghost_path_detection:
  enabled: true
  description: "Detect UI flows without real security backend"

  checks:
    - name: login_form_without_handler
      ui_pattern: "<form.*login|<button.*sign.?in"
      requires: "corresponding auth API endpoint"
      message: "Login form without authentication handler"

    - name: protected_route_without_guard
      ui_pattern: "ProtectedRoute|PrivateRoute|AuthRoute"
      requires: "route guard with actual auth check"
      message: "Protected route without real authorization"

    - name: permission_ui_without_backend
      ui_pattern: "hasPermission|canAccess|isAuthorized"
      requires: "backend permission verification"
      message: "Permission check in UI without backend validation"

  on_ghost:
    severity: warn
    message: |
      GHOST SECURITY PATH

      UI Element: {{ ui_element }}
      Missing: {{ missing_backend }}

      Security checks must be enforced on the backend.
      Client-side checks are supplementary only.

# ============================================
# REPORTING
# ============================================
reporting:
  on_block: |
    ## Security Gate Report

    **Timestamp**: {{ timestamp }}
    **File**: {{ file_path }}
    **Operation**: {{ operation }}
    **Outcome**: BLOCKED

    ### Reason
    {{ block_reason }}

    ### Required Actions
    1. {{ required_action_1 }}
    2. {{ required_action_2 }}

    ### Audit Trail
    - Blocked by: security-gate policy
    - Risk Grade: L3
    - Seal Status: {{ seal_status }}

    ---
    *Security is non-negotiable. All L3 operations require formal review.*

  on_stub_found: |
    ## Security Stub Alert

    **File**: {{ file_path }}
    **Line**: {{ line_number }}
    **Pattern**: {{ pattern_name }}

    ### Code Snippet
    ```
    {{ code_context }}
    ```

    ### Why This Is Blocked
    {{ explanation }}

    ### How To Fix
    {{ remediation }}

# ============================================
# EXCEPTIONS
# ============================================
exceptions:
  allowed_operations:
    - operation: read_file
      reason: "Reading security files for audit is allowed"

    - operation: grep
      reason: "Searching security files is allowed"

  test_files:
    patterns:
      - "**/tests/**"
      - "**/__tests__/**"
      - "**/*.test.*"
      - "**/*.spec.*"
      - "**/__mocks__/**"
    relaxations:
      - allow_mock_auth: true
      - allow_test_credentials: true
      - require_seal: false
    note: "Test files have relaxed security rules but still cannot have real credentials"
