name: Documentation
description: Report documentation issues or suggest improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve FailSafe documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Typo or grammar
        - Outdated content
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue?
      placeholder: "e.g., README.md, /docs/ARCHITECTURE_PLAN.md#section"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or improvement.
      placeholder: The documentation says X, but it should say Y...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: How would you improve it?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this change
          required: false
