name: Feature Request
description: Suggest a new feature or enhancement for FailSafe
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for FailSafe!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like FailSafe to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which FailSafe component does this relate to?
      options:
        - Governance (TrustEngine, EnforcementEngine)
        - Genesis (Dashboard, Panels)
        - QoreLogic (Ledger, Policies)
        - Sentinel (Pattern Detection)
        - Skills (/ql-* commands)
        - UI/UX
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
