name: cognitive-budget
version: "1.0.0"
description: "Context Management - prevent logic drift through budget tracking and resets"
id: QL-POLICY-005

enabled: true
priority: 4

triggers:
  - event: post_file_read
  - event: post_operation
  - event: periodic (every 5 operations)

# ============================================
# BUDGET METRICS
# ============================================
metrics:
  files_read:
    description: "Number of files read in current session"
    thresholds:
      info: 10
      warning: 15
      reset: 20
    on_threshold:
      info:
        action: log
        message: "{{ count }} files read. Context expanding."
      warning:
        action: alert
        severity: info
        message: "Approaching cognitive reset threshold ({{ count }}/20 files)"
      reset:
        action: cognitive_reset
        message: "Cognitive reset threshold reached. Re-centering on strategic docs."

  operations_count:
    description: "Total operations in current session"
    thresholds:
      checkpoint: 30
      warning: 50
      limit: 75
    on_threshold:
      checkpoint:
        action: suggest_checkpoint
        message: "Consider creating a checkpoint or partial substantiation"
      warning:
        action: alert
        severity: warn
        message: "High operation count. Consider breaking task into smaller iterations."
      limit:
        action: force_checkpoint
        message: "Operation limit reached. Creating forced checkpoint."

  complexity_score:
    description: "Cumulative complexity of operations"
    calculation: |
      score = 0
      for op in operations:
        if op.type == "read":
          score += 0.5
        elif op.type == "edit":
          score += 1
        elif op.type == "create":
          score += 1.5
        elif op.type == "delete":
          score += 2
        if op.path matches "*/security/*":
          score *= 1.5
    thresholds:
      warning: 15
      escalation: 25
    on_threshold:
      warning:
        action: alert
        message: "High complexity session. Consider simplifying approach."
      escalation:
        action: trigger_audit
        message: "Complexity threshold exceeded. Triggering internal audit."

  context_depth:
    description: "Depth of context tree (nested operations)"
    thresholds:
      warning: 5
      limit: 7
    on_threshold:
      warning:
        action: suggest_flatten
        message: "Deep context. Consider flattening approach."
      limit:
        action: force_flatten
        message: "Context too deep. Must complete current branch before proceeding."

# ============================================
# COGNITIVE RESET PROTOCOL
# ============================================
cognitive_reset:
  description: "Re-center on strategic documents to prevent drift"

  triggers:
    - files_read >= 20
    - operations_count >= 50
    - explicit_request

  protocol:
    steps:
      - name: alert_user
        action: notify
        message: |
          COGNITIVE RESET TRIGGERED

          Files read: {{ files_read }}
          Operations: {{ operations_count }}

          Re-centering on strategic alignment...

      - name: clear_low_priority
        action: context_manage
        clear:
          - "Low-level file contents from early turns"
          - "Intermediate computation results"
          - "Explored but unused alternatives"
        preserve:
          - "Current task context"
          - "Recent decisions"
          - "Active file contents"

      - name: reload_strategic
        action: read_files
        priority_files:
          - docs/CONCEPT.md
          - docs/ARCHITECTURE_PLAN.md
          - docs/SYSTEM_STATE.md
        purpose: "Re-anchor on strategic alignment"

      - name: reset_counters
        action: reset_metrics
        metrics:
          - files_read
          - operations_count
          - complexity_score

      - name: continue
        action: notify
        message: "Reset complete. Strategic context refreshed. Continuing..."

# ============================================
# CHECKPOINT SYSTEM
# ============================================
checkpoints:
  description: "Create save points during long sessions"

  triggers:
    - operations_count == 30
    - explicit_request
    - before_complex_operation

  create_checkpoint:
    steps:
      - name: capture_state
        action: compute
        state:
          files_modified: "{{ modified_files }}"
          current_phase: "{{ aegis_phase }}"
          pending_tasks: "{{ remaining_tasks }}"
          context_summary: "{{ summarize_context }}"

      - name: write_checkpoint
        action: create_file
        path: ".agent/checkpoints/checkpoint_{{ timestamp }}.json"
        content: "{{ state | json }}"

      - name: update_ledger
        action: append_ledger_entry
        type: CHECKPOINT
        content: "Session checkpoint at {{ timestamp }}"

  restore_checkpoint:
    steps:
      - name: load_checkpoint
        action: read_file
        path: "{{ checkpoint_path }}"

      - name: restore_state
        action: restore
        from: checkpoint

      - name: notify
        action: alert
        message: "Checkpoint restored from {{ checkpoint_time }}"

# ============================================
# DRIFT DETECTION
# ============================================
drift_detection:
  description: "Detect when operations drift from original intent"

  indicators:
    - name: scope_creep
      check: "Files modified outside blueprint"
      severity: warn

    - name: topic_drift
      check: "Recent operations unrelated to stated goal"
      severity: info

    - name: rabbit_hole
      check: "5+ operations on tangential issue"
      severity: warn

    - name: infinite_loop
      check: "Same file edited 3+ times without progress"
      severity: warn

  on_drift:
    action: alert
    message: |
      DRIFT DETECTED

      Type: {{ drift_type }}
      Original Goal: {{ original_goal }}
      Current Activity: {{ current_activity }}

      Consider:
      1. Return to original task
      2. Update goal if pivot is intentional
      3. Create separate task for tangent

# ============================================
# SESSION HEALTH
# ============================================
session_health:
  monitoring:
    - metric: files_read
      healthy: "< 15"
      warning: "15-20"
      critical: "> 20"

    - metric: operations_count
      healthy: "< 30"
      warning: "30-50"
      critical: "> 50"

    - metric: complexity_score
      healthy: "< 10"
      warning: "10-20"
      critical: "> 20"

    - metric: time_since_checkpoint
      healthy: "< 15min"
      warning: "15-30min"
      critical: "> 30min"

  dashboard: |
    ## Session Health

    | Metric | Value | Status |
    |--------|-------|--------|
    | Files Read | {{ files_read }}/20 | {{ files_status }} |
    | Operations | {{ ops_count }}/50 | {{ ops_status }} |
    | Complexity | {{ complexity }}/20 | {{ complexity_status }} |
    | Last Checkpoint | {{ checkpoint_age }} | {{ checkpoint_status }} |

    **Overall**: {{ overall_health }}

# ============================================
# REPORTING
# ============================================
reporting:
  on_reset: |
    ## Cognitive Reset Report

    **Triggered At**: {{ timestamp }}
    **Reason**: {{ trigger_reason }}

    ### Before Reset
    - Files Read: {{ before.files_read }}
    - Operations: {{ before.operations }}
    - Complexity: {{ before.complexity }}

    ### After Reset
    - Strategic docs refreshed
    - Counters reset
    - Context re-centered

    ### Continuing With
    - Task: {{ current_task }}
    - Phase: {{ current_phase }}

  on_checkpoint: |
    ## Checkpoint Created

    **Time**: {{ timestamp }}
    **Checkpoint ID**: {{ checkpoint_id }}

    ### State Captured
    - Modified Files: {{ files_count }}
    - Current Phase: {{ phase }}
    - Pending Tasks: {{ pending_count }}

    To restore: Use checkpoint ID {{ checkpoint_id }}

# ============================================
# CONFIGURATION
# ============================================
configuration:
  auto_reset: true
  auto_checkpoint: true
  checkpoint_interval: 30  # operations
  reset_threshold: 20  # files
  alert_on_drift: true
