name: aegis-implement
version: "1.0.0"
description: Specialist Implementation Pass - build with §4 Simplicity Razor and TDD-Light
phase: IMPLEMENT
orbit: orbit-specialist
risk_grade: L2

triggers:
  - command: "/aegis-implement"
  - command: "/implement"
  - condition: "audit_verdict == 'PASS'"

inputs:
  target:
    type: string
    required: false
    description: Specific file or component to implement

outputs:
  - src/* (source code)
  - tests/* (test files)
  - docs/META_LEDGER.md (updated)

preconditions:
  - name: gate_passed
    check: ".agent/staging/AUDIT_REPORT.md"
    expect: "exists AND contains 'VERDICT: PASS'"
    on_fail:
      action: abort
      message: "Gate locked. Tribunal audit required. Run /aegis-gate first."

  - name: blueprint_exists
    check: "docs/ARCHITECTURE_PLAN.md"
    expect: "exists"
    on_fail:
      action: abort
      message: "No blueprint found. Complete ENCODE phase first."

steps:
  - id: activate_specialist
    name: Identity Activation
    action: activate_orbit
    orbit: orbit-specialist
    mode: "Zero Fluff - Build"

  - id: load_blueprint
    name: Load Blueprint
    action: read_file
    path: docs/ARCHITECTURE_PLAN.md
    extract:
      - pattern: "File Tree[\\s\\S]*?```([\\s\\S]*?)```"
        variable: planned_files
      - pattern: "Risk Grade: (L[123])"
        variable: risk_grade
      - pattern: "Interface Contracts[\\s\\S]*?(###|$)"
        variable: interfaces

  - id: verify_build_path
    name: Trace Build Path
    action: verify_connectivity
    entry_points:
      - src/index.ts
      - src/main.tsx
      - index.ts
    target: "{{ target }}"
    on_orphan:
      action: abort
      message: "Target file would be orphaned. Verify import chain or update blueprint."

  - id: tdd_light
    name: TDD-Light - Write Failing Test
    action: create_file
    condition: "target.type == 'logic'"
    path: "tests/{{ target.name }}.test.ts"
    content: |
      describe('{{ target.name }}', () => {
        it('should {{ success_condition_from_blueprint }}', () => {
          // Arrange
          const input = {{ test_input }};

          // Act
          const result = {{ target.function }}(input);

          // Assert
          expect(result).toBe({{ expected_output }});
        });
      });
    note: "Minimal failing test with ONE success condition"

  - id: implementation_loop
    name: Precision Build Loop
    action: loop
    for_each: "{{ planned_files }}"
    steps:
      - id: check_razor_pre
        name: Pre-Implementation Razor Check
        action: validate
        policy: kiss-razor
        on_violation: "Halt and split design"

      - id: implement_file
        name: Implement File
        action: create_or_edit_file
        path: "{{ file.path }}"
        constraints:
          max_function_lines: 40
          max_file_lines: 250
          max_nesting: 3
          forbidden_patterns:
            - nested_ternary: "\\?[^:]+:[^?]+\\?"
            - generic_vars: "\\b(x|data|obj|temp|item|result)\\s*="
            - console_log: "console\\.log"
        naming_rules:
          variables: "noun or verbNoun"
          functions: "verbNoun"
        visual_silence:
          colors: "var(--color-*)"
          sizes: "var(--spacing-*)"

      - id: check_razor_post
        name: Post-Implementation Razor Check
        action: validate
        policy: kiss-razor
        on_violation:
          action: auto_refactor
          workflow: aegis-refactor
          target: "{{ file.path }}"

  - id: cleanup_pass
    name: Post-Build Cleanup
    action: cleanup
    targets:
      - pattern: "console\\.log"
        action: remove
        reason: "Debug artifacts"
      - pattern: "// TODO"
        action: warn
        reason: "Incomplete implementation"
      - pattern: "// @ts-ignore"
        action: warn
        reason: "Type safety bypass"
    verify:
      - "No console.log statements"
      - "No commented-out code blocks > 3 lines"
      - "No unrequested configuration"

  - id: run_tests
    name: Verify Tests Pass
    action: execute
    command: "npm test -- --testPathPattern={{ target.name }}"
    on_fail:
      action: loop_back
      to: implementation_loop
      message: "Test failed. Revise implementation."

  - id: complexity_self_check
    name: Final Complexity Self-Check
    action: analyze
    for_each: "{{ modified_files }}"
    metrics:
      - function_lines
      - nesting_depth
      - cyclomatic_complexity
    thresholds:
      function_lines: 40
      nesting_depth: 3
      cyclomatic_complexity: 10
    on_violation:
      action: auto_refactor
      workflow: aegis-refactor

  - id: update_ledger
    name: Update Merkle Ledger
    action: append_ledger_entry
    path: docs/META_LEDGER.md
    entry:
      id: "{{ next_entry_id }}"
      timestamp: "{{ ISO_8601_NOW }}"
      phase: IMPLEMENT
      author: Specialist
      risk_grade: "{{ risk_grade }}"
      files_modified: "{{ modified_files | join(', ') }}"
      content_hash: "{{ compute_hash(modified_files) }}"
      previous_hash: "{{ previous_entry_hash }}"
      chain_hash: "{{ compute_chain_hash(content_hash, previous_entry_hash) }}"
      decision: "Implementation complete. §4 Razor applied."

  - id: handoff
    name: Handoff to Judge
    action: output
    format: |
      ## Implementation Complete

      **Files Created/Modified**:
      | File | Lines | Max Nesting | Status |
      |------|-------|-------------|--------|
      {% for f in modified_files %}
      | {{ f.path }} | {{ f.lines }}/250 | {{ f.nesting }}/3 | ✓ |
      {% endfor %}

      **Tests**:
      | Test File | Passing |
      |-----------|---------|
      {% for t in test_files %}
      | {{ t.path }} | {{ '✓' if t.passing else '✗' }} |
      {% endfor %}

      **§4 Razor Compliance**: VERIFIED

      ### Next Action
      Implementation complete. The Judge must now invoke /aegis-substantiate to verify and seal.

      ---
      *Reality built. Awaiting substantiation.*

  - id: invoke_substantiate
    name: Trigger Substantiation
    action: suggest_next
    workflow: aegis-substantiate
    message: "Ready for substantiation. Run /aegis-substantiate to seal."

postconditions:
  - name: files_created
    check: "{{ planned_files }} all exist in src/"
    expect: "true"

  - name: tests_exist
    check: "tests/*.test.ts exists for each logic component"
    expect: "true"

  - name: razor_compliant
    check: "All files pass kiss-razor policy"
    expect: "true"

error_handling:
  on_razor_violation:
    action: suggest_refactor
    workflow: aegis-refactor
    message: "§4 violation detected. Auto-refactor suggested."

  on_test_failure:
    action: loop_back
    message: "Tests failing. Implementation incomplete."

  on_build_error:
    action: invoke_debug
    workflow: debug-protocol
    message: "Build error. Triggering debug protocol."
