name: aegis-gate
version: "1.0.0"
description: A.E.G.I.S. Gate Tribunal - adversarial audit generating PASS/VETO verdict
phase: GATE
orbit: orbit-judge
risk_grade: L2

triggers:
  - command: "/aegis-gate"
  - command: "/audit"
  - condition: "risk_grade in ['L2', 'L3'] AND audit_required"

inputs:
  target:
    type: string
    required: false
    description: Specific component to audit (defaults to full blueprint)

outputs:
  - .agent/staging/AUDIT_REPORT.md
  - docs/META_LEDGER.md (updated)
  - docs/SHADOW_GENOME.md (if VETO)

preconditions:
  - name: blueprint_exists
    check: "docs/ARCHITECTURE_PLAN.md"
    expect: "exists"
    on_fail:
      action: abort
      message: "No blueprint found. Governor must complete ENCODE phase first."

  - name: ledger_exists
    check: "docs/META_LEDGER.md"
    expect: "exists"
    on_fail:
      action: abort
      message: "No ledger found. Run /aegis-bootstrap first."

steps:
  - id: activate_judge
    name: Identity Activation
    action: activate_orbit
    orbit: orbit-judge
    mode: "Adversarial"
    note: "Find violations, not improvements"

  - id: load_state
    name: State Verification
    action: read_files
    files:
      - path: docs/ARCHITECTURE_PLAN.md
        variable: blueprint
      - path: docs/META_LEDGER.md
        variable: ledger
      - path: docs/CONCEPT.md
        variable: concept

  - id: extract_risk
    name: Extract Risk Grade
    action: extract
    from: blueprint
    pattern: "Risk Grade: (L[123])"
    variable: risk_grade

  - id: security_pass
    name: Security Audit Pass
    action: audit
    type: security
    checks:
      - name: placeholder_auth
        pattern: ["TODO.*auth", "FIXME.*auth", "// implement auth"]
        paths: ["**/*.ts", "**/*.js", "**/*.py"]
        on_found: VETO
        reason: "Security placeholder detected"

      - name: hardcoded_secrets
        pattern: ["password\\s*=\\s*['\"]", "api_key\\s*=\\s*['\"]", "secret\\s*=\\s*['\"]"]
        on_found: VETO
        reason: "Hardcoded credential detected"

      - name: bypass_checks
        pattern: ["// security disabled", "// skip auth", "return true // temp"]
        on_found: VETO
        reason: "Security bypass detected"

      - name: mock_auth
        pattern: ["mock.*auth", "fake.*token", "test.*credential"]
        paths: ["*/security/*", "*/auth/*"]
        on_found: VETO
        reason: "Mock authentication in security path"
    output: security_result

  - id: ghost_ui_pass
    name: Ghost UI Audit Pass
    action: audit
    type: ghost_paths
    checks:
      - name: button_handlers
        check: "Every <button> has onClick mapped to real logic"
        on_violation: VETO
        reason: "Button without handler"

      - name: form_handlers
        check: "Every <form> has onSubmit with real processing"
        on_violation: VETO
        reason: "Form without submission logic"

      - name: placeholder_ui
        pattern: ["coming soon", "placeholder", "TODO: implement"]
        on_found: VETO
        reason: "Placeholder UI detected"
    output: ghost_result

  - id: kiss_razor_pass
    name: ยง4 Simplicity Razor Pass
    action: audit
    type: kiss_compliance
    checks:
      - name: function_length
        max: 40
        unit: lines
        on_violation: VETO
        reason: "Function exceeds 40 lines"

      - name: file_length
        max: 250
        unit: lines
        on_violation: VETO
        reason: "File exceeds 250 lines"

      - name: nesting_depth
        max: 3
        unit: levels
        on_violation: VETO
        reason: "Nesting exceeds 3 levels"

      - name: nested_ternary
        pattern: "\\?[^:]+:[^?]+\\?"
        on_found: VETO
        reason: "Nested ternary detected"
    output: kiss_result

  - id: dependency_pass
    name: Dependency Audit Pass
    action: audit
    type: dependencies
    checks:
      - name: justified
        check: "Each dependency has documented justification"
        on_violation: VETO
        reason: "Unjustified dependency"

      - name: vanilla_possible
        check: "No dependency replaceable by <10 lines vanilla"
        on_violation: VETO
        reason: "Unnecessary dependency"

      - name: hallucinated
        check: "All dependencies exist in registry"
        on_violation: VETO
        reason: "Non-existent dependency"
    output: dependency_result

  - id: orphan_pass
    name: Build Path Audit Pass
    action: audit
    type: orphan_detection
    entry_points: ["src/index.ts", "src/main.tsx", "index.ts"]
    check: "All proposed files reachable from entry point"
    on_orphan: VETO
    reason: "Proposed file would be orphaned"
    output: orphan_result

  - id: aggregate_verdict
    name: Aggregate Verdict
    action: compute
    logic: |
      if any([security_result.veto, ghost_result.veto, kiss_result.veto,
              dependency_result.veto, orphan_result.veto]):
        verdict = "VETO"
        violations = collect_all_violations()
      else:
        verdict = "PASS"
        violations = []
    output: final_verdict

  - id: generate_report
    name: Generate Audit Report
    action: create_file
    path: .agent/staging/AUDIT_REPORT.md
    content: |
      # AUDIT REPORT

      **Tribunal Date**: {{ ISO_8601_NOW }}
      **Target**: {{ target | default('Full Blueprint') }}
      **Risk Grade**: {{ risk_grade }}
      **Auditor**: The QoreLogic Judge

      ---

      ## VERDICT: {{ final_verdict.verdict }}

      ---

      ### Executive Summary
      {{ executive_summary }}

      ### Audit Results

      #### Security Pass
      **Result**: {{ 'FAIL' if security_result.veto else 'PASS' }}
      {{ security_result.findings | join('\n') }}

      #### Ghost UI Pass
      **Result**: {{ 'FAIL' if ghost_result.veto else 'PASS' }}
      {{ ghost_result.findings | join('\n') }}

      #### ยง4 Razor Pass
      **Result**: {{ 'FAIL' if kiss_result.veto else 'PASS' }}
      {{ kiss_result.findings | join('\n') }}

      #### Dependency Pass
      **Result**: {{ 'FAIL' if dependency_result.veto else 'PASS' }}
      {{ dependency_result.findings | join('\n') }}

      #### Orphan Pass
      **Result**: {{ 'FAIL' if orphan_result.veto else 'PASS' }}
      {{ orphan_result.findings | join('\n') }}

      ### Violations Found

      | ID | Category | Location | Description |
      |----|----------|----------|-------------|
      {% for v in violations %}
      | V{{ loop.index }} | {{ v.category }} | {{ v.location }} | {{ v.description }} |
      {% endfor %}

      {% if final_verdict.verdict == 'VETO' %}
      ### Required Remediation

      {% for v in violations %}
      {{ loop.index }}. {{ v.remediation }}
      {% endfor %}
      {% endif %}

      ### Verdict Hash
      ```
      SHA256(this_report) = {{ report_hash }}
      ```

      ---
      *This verdict is binding. Implementation may {{ 'proceed' if final_verdict.verdict == 'PASS' else 'NOT proceed' }}.*

  - id: update_ledger
    name: Update Merkle Ledger
    action: append_ledger_entry
    path: docs/META_LEDGER.md
    entry:
      id: "{{ next_entry_id }}"
      timestamp: "{{ ISO_8601_NOW }}"
      phase: GATE
      author: Judge
      risk_grade: "{{ risk_grade }}"
      verdict: "{{ final_verdict.verdict }}"
      content_hash: "{{ report_hash }}"
      previous_hash: "{{ previous_entry_hash }}"
      chain_hash: "{{ compute_chain_hash(report_hash, previous_entry_hash) }}"
      decision: "Gate Tribunal: {{ final_verdict.verdict }}"

  - id: update_shadow_genome
    name: Update Shadow Genome (if VETO)
    action: conditional
    if: "{{ final_verdict.verdict }} == 'VETO'"
    then:
      action: append_file
      path: docs/SHADOW_GENOME.md
      content: |
        ---

        ## Failure Entry #{{ next_failure_id }}

        **Date**: {{ ISO_8601_NOW }}
        **Verdict ID**: {{ report_hash[:8] }}
        **Failure Mode**: {{ violations[0].category }}

        ### What Failed
        {{ target | default('Blueprint') }}

        ### Why It Failed
        {% for v in violations %}
        - {{ v.description }}
        {% endfor %}

        ### Pattern to Avoid
        {{ generalized_lesson }}

        ### Remediation Attempted
        Pending - requires blueprint revision

  - id: final_output
    name: Output Verdict
    action: output
    format: |
      ## Tribunal Complete

      **Verdict**: {{ final_verdict.verdict }}
      **Risk Grade**: {{ risk_grade }}
      **Report Location**: .agent/staging/AUDIT_REPORT.md

      {% if final_verdict.verdict == 'PASS' %}
      Gate cleared. The Specialist may proceed with /aegis-implement.
      {% else %}
      Implementation blocked. Address violations and re-submit for audit.
      Required actions logged in AUDIT_REPORT.md.
      Failure mode recorded in SHADOW_GENOME.md.
      {% endif %}

      ---
      *Gate {{ 'OPEN' if final_verdict.verdict == 'PASS' else 'LOCKED' }}. Proceed accordingly.*

postconditions:
  - name: report_created
    check: ".agent/staging/AUDIT_REPORT.md"
    expect: "exists"

  - name: ledger_updated
    check: "docs/META_LEDGER.md contains {{ report_hash }}"
    expect: "true"

error_handling:
  on_audit_error:
    action: abort
    message: "Audit failed. Unable to complete tribunal."
