name: aegis-triage
version: "1.0.0"
description: Request Classification and Routing - analyze requests and assign appropriate workflow
phase: PRE-LIFECYCLE
orbit: orbit-sentinel
risk_grade: L1

triggers:
  - condition: "new_user_request"
  - condition: "task_received"

inputs:
  request:
    type: string
    required: true
    description: User request or task description
  context:
    type: object
    required: false
    description: Additional context (files, history)

outputs:
  - Routing decision
  - Risk classification
  - Workflow assignment

steps:
  - id: activate_sentinel
    name: Activate Routing Engine
    action: activate_orbit
    orbit: orbit-sentinel
    mode: "Triage"

  - id: check_initialization
    name: Check Project Initialization
    action: check_files
    files:
      - path: docs/META_LEDGER.md
        variable: is_initialized
    on_not_initialized:
      route_to: aegis-bootstrap
      message: "Project not initialized. Starting bootstrap..."

  - id: classify_request
    name: Classify Request Type
    action: analyze
    input: "{{ request }}"
    classifications:
      - type: new_feature
        indicators: ["add", "create", "implement", "build", "new"]
        workflow: aegis-bootstrap  # Start from ALIGN
        risk_default: L2

      - type: bug_fix
        indicators: ["fix", "bug", "broken", "error", "crash", "fails"]
        workflow: aegis-encode  # May skip ALIGN if scope clear
        risk_default: L1

      - type: refactor
        indicators: ["refactor", "clean", "simplify", "restructure", "optimize"]
        workflow: aegis-refactor
        risk_default: L1

      - type: security
        indicators: ["auth", "security", "permission", "credential", "encrypt"]
        workflow: aegis-gate  # Require audit first
        risk_default: L3

      - type: documentation
        indicators: ["document", "readme", "comment", "explain"]
        workflow: aegis-encode
        risk_default: L1

      - type: query
        indicators: ["what", "how", "why", "where", "explain", "?"]
        workflow: none  # Direct response, no lifecycle
        risk_default: L1

    output: classification

  - id: assess_complexity
    name: Assess Complexity
    action: compute
    factors:
      - name: file_count
        weight: 1
        thresholds: {low: 3, medium: 10, high: 20}
      - name: cross_module
        weight: 2
        check: "affects multiple directories"
      - name: api_changes
        weight: 2
        check: "modifies interfaces or contracts"
      - name: data_schema
        weight: 2
        check: "affects data structures"
      - name: security_impact
        weight: 3
        check: "touches security or auth"
    calculate: |
      score = sum(factor.weight * factor.value for factor in factors)
      if score <= 3: complexity = "LOW"
      elif score <= 7: complexity = "MEDIUM"
      else: complexity = "HIGH"
    output: complexity

  - id: determine_risk
    name: Determine Risk Grade
    action: compute
    logic: |
      # Start with classification default
      risk = classification.risk_default

      # Escalate based on complexity
      if complexity == "HIGH" and risk == "L1":
        risk = "L2"

      # Escalate based on path patterns
      if any(p in request for p in ["security", "auth", "credential", "pii"]):
        risk = "L3"

      # Escalate based on irreversibility
      if any(p in request for p in ["delete", "drop", "remove", "migrate"]):
        risk = max(risk, "L2")
    output: risk_grade

  - id: select_orbit
    name: Select Active Orbit
    action: conditional
    conditions:
      - if: "{{ classification.type }} == 'security' OR {{ risk_grade }} == 'L3'"
        then: orbit-judge
      - if: "{{ classification.type }} in ['new_feature', 'documentation']"
        then: orbit-governor
      - if: "{{ classification.type }} in ['bug_fix', 'refactor']"
        then: orbit-specialist
      - else: orbit-governor
    output: assigned_orbit

  - id: select_workflow
    name: Select Workflow
    action: conditional
    conditions:
      - if: "{{ is_initialized }} == false"
        then: aegis-bootstrap

      - if: "{{ risk_grade }} == 'L3'"
        then: aegis-gate  # Always gate L3

      - if: "{{ classification.type }} == 'refactor'"
        then: aegis-refactor

      - if: "{{ classification.type }} == 'query'"
        then: null  # Direct response

      - if: "{{ complexity }} == 'HIGH'"
        then: aegis-bootstrap  # Full lifecycle for complex

      - if: "{{ complexity }} == 'MEDIUM' AND {{ risk_grade }} == 'L2'"
        then: aegis-gate  # Gate medium L2

      - if: "{{ complexity }} == 'LOW' AND {{ risk_grade }} == 'L1'"
        then: aegis-implement  # Fast path for simple L1

      - else: aegis-encode
    output: assigned_workflow

  - id: check_existing_state
    name: Check Existing State
    action: check_files
    files:
      - path: .agent/staging/AUDIT_REPORT.md
        variable: has_audit
        extract_verdict: true
    logic: |
      if has_audit and audit_verdict == "PASS":
        # Can skip to implement if blueprint unchanged
        if assigned_workflow == "aegis-encode":
          assigned_workflow = "aegis-implement"

  - id: generate_routing
    name: Generate Routing Decision
    action: output
    format: |
      ## Triage Complete

      **Request**: {{ request[:100] }}...

      ### Classification

      | Attribute | Value |
      |-----------|-------|
      | Type | {{ classification.type }} |
      | Complexity | {{ complexity }} |
      | Risk Grade | {{ risk_grade }} |

      ### Routing

      | Decision | Value |
      |----------|-------|
      | Orbit | {{ assigned_orbit }} |
      | Workflow | {{ assigned_workflow | default('Direct Response') }} |
      | Gate Required | {{ 'Yes' if risk_grade in ['L2', 'L3'] else 'No' }} |

      ### Rationale
      {{ routing_rationale }}

      ---
      {% if assigned_workflow %}
      *Proceeding to {{ assigned_workflow }}...*
      {% else %}
      *Processing request directly...*
      {% endif %}

  - id: invoke_workflow
    name: Invoke Selected Workflow
    action: conditional
    if: "{{ assigned_workflow }} != null"
    then:
      action: invoke_workflow
      workflow: "{{ assigned_workflow }}"
      orbit: "{{ assigned_orbit }}"
      context:
        request: "{{ request }}"
        risk_grade: "{{ risk_grade }}"
        complexity: "{{ complexity }}"

postconditions: []

error_handling:
  on_classification_failure:
    action: default
    workflow: aegis-bootstrap
    message: "Could not classify request. Starting full lifecycle."

  on_orbit_conflict:
    action: escalate
    to: orbit-governor
    message: "Multiple orbits applicable. Governor will decide."
