import * as fs from 'fs';
import * as path from 'path';
import { SystemRegistry, AgentLandscape } from './SystemRegistry';

export class AgentsMarkdownGenerator {
  constructor(private readonly systemRegistry: SystemRegistry) {}

  async generate(): Promise<string> {
    const landscape = await this.systemRegistry.detectAll();
    return this.renderMarkdown(landscape);
  }

  async write(workspaceRoot: string): Promise<void> {
    const content = await this.generate();
    const outputPath = path.join(workspaceRoot, 'AGENTS.md');
    await fs.promises.writeFile(outputPath, content, 'utf-8');
  }

  private renderMarkdown(landscape: AgentLandscape): string {
    const lines: string[] = [
      '# Agents',
      '',
      '> Auto-generated by FailSafe governance. Do not edit manually.',
      '',
      '## Registered Systems',
      '',
      '| Agent | ID | Governed |',
      '|-------|----|----------|',
    ];

    for (const system of landscape.registeredSystems) {
      const m = system.getManifest();
      const governed = this.systemRegistry.hasGovernance(system) ? 'Yes' : 'No';
      lines.push(`| ${m.name} | ${m.id} | ${governed} |`);
    }

    lines.push('', '## Active Terminals', '');
    if (landscape.activeTerminals.length === 0) {
      lines.push('No agent terminals detected.');
    } else {
      lines.push('| Terminal | Agent Type |', '|----------|-----------|');
      for (const t of landscape.activeTerminals) {
        lines.push(`| ${t.name} | ${t.agentType} |`);
      }
    }

    lines.push('', '## Agent Teams', '');
    lines.push(`Status: ${landscape.agentTeams.enabled ? 'Enabled' : 'Disabled'}`);
    lines.push(`Settings: ${landscape.agentTeams.settingsPath}`);
    lines.push('');

    return lines.join('\n');
  }
}
